### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by exbe** [ewfian/How-to-create-newline-in-Github-Bio#2]
It just displays \&nbsp;  in the output.

**Comment by experdot** [comment]
@exbe It works well.
### Preview
![image](https://user-images.githubusercontent.com/9404172/38469469-dce74bb6-3b87-11e8-8501-6e1c5d580de1.png)
### HTML
![image](https://user-images.githubusercontent.com/9404172/38469476-f69e58e2-3b87-11e8-9c66-caecae6eb261.png)

**Comment by dideler** [comment]
Make sure you're doing it on https://github.com/settings/profile.

It won't work when editing your bio directly on `https://github.com/<username>`.

**Comment by zhanzengyu** [comment]
@exbe won't work for me, too

**Comment by bmitchinson** [comment]
Still works for me, see my bio.

I just inserted a view using chrome dev tools at https://github.com/settings/profile, then just copy and pasted them without using the html editor in the field itself.

**Comment by jaykay12** [comment]
It works like a charm! Thank you @ewfian :+1:

**Comment by exbe** [comment]
Yep, I have got it working for me too. I wrongly assumed that in chrome inline edit works same as **[Edit as HTML]**

**Comment by zhanzengyu** [comment]
> @exbe won't work for me, too

All right，I forgot to place a space at the beginning of the second line.
It works well!
